config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create]
  end

  resources :posts do
    resources :comments, only: [:create]
    resources :likes, only: [:create]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  # Validations
  validates :author_id, presence: true
  validates :post_id, presence: true
  validates :text, presence: true

  after_save :update_comment_counter

  def update_comment_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  # validations
  validates :author_id, presence: true
  validates :post_id, presence: true

  after_save :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes, dependent: :destroy, class_name: 'Like'
  has_many :comments, dependent: :destroy, class_name: 'Comment'

  after_save :update_user_posts

  def update_user_posts
    author.increment!(:posts_counter)
  end

  # Post validations
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, :likes_counter,
            numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def recent_comments
    comments.limit(5).order(created_at: :desc)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  # user validations
  validates :name, :bio, presence: true
  validates :email, uniqueness: true
  validates :posts_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def recent_posts
    posts.includes(:comments, :likes).order(created_at: :asc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email name bio password password_confirmation])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    redirect_to user_posts_path(id: @comment.post_id, user_id: @comment.author_id) if @comment.save
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :author_id, :post_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new(like_params)
    redirect_to user_posts_path(id: @like.post_id, user_id: @like.author_id) if @like.save
  end

  private

  def like_params
    params.require(:like).permit(:author_id, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @user_posts = @user.recent_posts
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @like = Like.new
  end

  def new
    @post = Post.new
    @params = params
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to user_post_path(id: @post.id, user_id: @post.author_id), notice: 'Post was successfully created.'
    else
      render :new, alert: 'Error occurred, Post not saved'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :author_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(:name)
  end

  def show
    @user = User.find(params[:id])
    @recent_posts = @user.recent_posts
  end
end

app/helpers/application_helper.rb
# rubocop: nodoc
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="notice-center">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/partials/_post.html.erb
<article class="post-snipet">
    <h3><%= link_to(post.title, user_post_path(id: post.id, user_id: post.author_id)) %></h3>
    <p><%= truncate(post.text, length: 125) ... %></p>
    <div class="post-stats">
      <span>Comments <%= post.comments_counter %> &nbsp;,&nbsp;</span>
      <span>Likes <%= post.likes_counter %></span>
    </div>
  </article>

app/views/partials/_user.html.erb
<%= stylesheet_link_tag('user') %>
<section class="user">
  <%= image_tag('user.png', class:'user_picture') %>
  <div class="content">
    <h2><%= link_to(user.name, user_path(user)) %></h2>
    <p>
      Number of posts: <%= user.posts_counter %>
    </p>
  </div>
</section>

app/views/posts/index.html.erb
<%= render partial: 'partials/user', locals: { user: @user } %>
<%  @user_posts.each do |post| %>
    <%= render partial: 'partials/post', locals: { post: post} %>
      <ul class="comments">
      <% post.recent_comments.each do |comment| %>
        <li><%= comment.author.name %>: <%= comment.text %>
      <% end %>
      </ul>
<% end %>

<%= link_to "Add Post", new_user_post_path(@user), class: "see-all-btn"%>

app/views/posts/new.html.erb
<%= form_for @post, url: user_posts_path do |f| %>
<h2>Create new post article</h2>
  <% if @post.errors.any? %>
    <ul class="errors">
      <% @post.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  <% end %>
  <%= f.hidden_field :author_id, value: @params ? @params['user_id'] : '' %>
  <div>
    <%= f.label :title %><br />
    <%= f.text_field :title, placeholder: 'Article title' %>
  </div>
  <div>
    <%= f.label :text, "Description" %><br />
    <%= f.text_area :text, placeholder: 'Type your article message in here...' %>
  </div>
  <%= f.submit "Submit post", disable_with: 'Submiting...' %>
<% end %> 

app/views/posts/show.html.erb
<article class="post-snipet">
  <h3><%= @post.title %>  by <%= link_to @post.author.name, user_path(@post.author_id) %></h3>
    <div class="post-stats">
      <span>Comments <%= @post.comments_counter %> &nbsp;,&nbsp;</span>
      <span>Likes <%= @post.likes_counter %></span>
    </div>
    <p><%= @post.text %></p>
  </article>
  <%= form_for @like, url:post_likes_path(@post) do |f|%>
  <%= f.hidden_field :author_id, value: @post.author.id %>
  <%= f.hidden_field :post_id, value: @post.id %>
  <%= f.submit "Like", class:'btn', disable_with: 'updating likes...' %>
<% end %>
  <ul class="comments">
    <% @post.recent_comments.each do |comment| %>
      <li><%= comment.author.name %>: <%= comment.text %>
    <% end %>
  </ul>
  <h4>Add Comment</h4>
  <%= form_for @comment, url:post_comments_path(@post) do |f| %>
    <%= f.hidden_field :author_id, value: @post.author.id %>
    <%= f.hidden_field :post_id, value: @post.id %>
    <%= f.label :text %><br />
    <%= f.text_area :text, placeholder:'What are your thoughts on this post?' %><br />
    <%= f.submit "Submit comment", class:"btn see-all-btn", disable_with: 'Submiting Comment...' %>
  <% end %>



  

app/views/users/index.html.erb
<% @users.each do |user| %>
<%= render partial: 'partials/user', locals: { user: user } %>
<% end %>
Footer

app/views/users/show.html.erb
<%= render partial: 'partials/user', locals: { user: @user }%>
<div class='bio'>
  <b>Bio</b>
  <p><%= @user.bio %></p>
</div>
<% @recent_posts.each do |post| %>
  <%= render partial: 'partials/post', locals: { post: post} %>
<% end %>
<%= link_to("see all posts", user_posts_path(@user), class: "see-all-btn") %>